version: "3.9"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: cryptocurrency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0
    ports: ["5000:5000"]
    volumes: ["./mlruns:/mlruns"]

  trainer:
    build: .
    environment:
      POSTGRES_URI: postgresql://postgres:admin@postgres:5432/cryptocurrency
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - .:/app
    depends_on: [postgres, mlflow]

volumes:
  pgdata:
